### ISSUE TITLE
Addon not updating games

### ISSUE THREAD

**Issue by rjhartman74** [eracknaphobia/plugin.video.nbcsnliveextra#5]
the nbcsn addon is not updating games.  It currently shows games from the end of October through the end of November.  thanks for all of your hard work!

**Comment by eracknaphobia** [comment]
Just want to let you know I've been working on updating the addon. I've got new items showing up and playing but I'd like to get drm streams to work as well. So it may be a bit longer before I have all the kinks worked out.

**Comment by rjhartman74** [comment]
Thank you for the update!!
